// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	SearchQuery          string   `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSearchQuery() string {
	if m != nil {
		return m.SearchQuery
	}
	return ""
}

type Response struct {
	RelevantDocuments    []*Response_DocumentStats `protobuf:"bytes,1,rep,name=relevant_documents,json=relevantDocuments,proto3" json:"relevant_documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRelevantDocuments() []*Response_DocumentStats {
	if m != nil {
		return m.RelevantDocuments
	}
	return nil
}

type Response_DocumentStats struct {
	DocumentName         string   `protobuf:"bytes,1,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Score                float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	DocumentSize         int64    `protobuf:"varint,3,opt,name=document_size,json=documentSize,proto3" json:"document_size,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_DocumentStats) Reset()         { *m = Response_DocumentStats{} }
func (m *Response_DocumentStats) String() string { return proto.CompactTextString(m) }
func (*Response_DocumentStats) ProtoMessage()    {}
func (*Response_DocumentStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1, 0}
}
func (m *Response_DocumentStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_DocumentStats.Unmarshal(m, b)
}
func (m *Response_DocumentStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_DocumentStats.Marshal(b, m, deterministic)
}
func (m *Response_DocumentStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_DocumentStats.Merge(m, src)
}
func (m *Response_DocumentStats) XXX_Size() int {
	return xxx_messageInfo_Response_DocumentStats.Size(m)
}
func (m *Response_DocumentStats) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_DocumentStats.DiscardUnknown(m)
}

var xxx_messageInfo_Response_DocumentStats proto.InternalMessageInfo

func (m *Response_DocumentStats) GetDocumentName() string {
	if m != nil {
		return m.DocumentName
	}
	return ""
}

func (m *Response_DocumentStats) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Response_DocumentStats) GetDocumentSize() int64 {
	if m != nil {
		return m.DocumentSize
	}
	return 0
}

func (m *Response_DocumentStats) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "model.Request")
	proto.RegisterType((*Response)(nil), "model.Response")
	proto.RegisterType((*Response_DocumentStats)(nil), "model.Response.DocumentStats")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x79, 0x8e, 0xad, 0xfa, 0xa6, 0x5d, 0x18, 0x44, 0x82, 0x20, 0xc4, 0xba, 0xc9, 0x42,
	0x66, 0xa1, 0x57, 0x70, 0x29, 0x82, 0xe9, 0x01, 0x86, 0x38, 0x7d, 0xd0, 0x42, 0x93, 0xb4, 0x79,
	0x89, 0x60, 0x2f, 0xe0, 0x3d, 0x3d, 0x89, 0x38, 0x33, 0xa1, 0x74, 0xf9, 0x7f, 0xfc, 0xdf, 0x9f,
	0xf0, 0xb0, 0x76, 0x61, 0x45, 0xdb, 0x66, 0x17, 0x43, 0x0a, 0x62, 0xd2, 0x87, 0xc5, 0x13, 0x5e,
	0x18, 0xda, 0x67, 0xe2, 0x24, 0x1e, 0x70, 0xc6, 0x64, 0x63, 0xb7, 0x6e, 0xf7, 0x99, 0xe2, 0xb7,
	0x04, 0x05, 0xfa, 0xca, 0xd4, 0x03, 0xfb, 0xf8, 0x47, 0x8b, 0x5f, 0xc0, 0x4b, 0x43, 0xbc, 0x0b,
	0x9e, 0x49, 0xbc, 0xa1, 0x88, 0xb4, 0xa5, 0x2f, 0xeb, 0x53, 0xbb, 0x0a, 0x5d, 0x76, 0xe4, 0x13,
	0x4b, 0x50, 0x95, 0xae, 0x9f, 0xef, 0x9b, 0xe1, 0xad, 0x52, 0x6e, 0x5e, 0xc7, 0xc2, 0x32, 0xd9,
	0xc4, 0xe6, 0xba, 0x88, 0x05, 0xf3, 0xdd, 0x0f, 0xe0, 0xfc, 0xa4, 0x24, 0x1e, 0x71, 0x5e, 0x66,
	0x5b, 0x6f, 0x1d, 0x8d, 0x1f, 0x9a, 0x15, 0xf8, 0x6e, 0x1d, 0x89, 0x1b, 0x9c, 0x70, 0x17, 0x22,
	0xc9, 0x33, 0x05, 0x1a, 0xcc, 0x10, 0x4e, 0x54, 0xde, 0x1c, 0x48, 0x56, 0x0a, 0x74, 0x75, 0x54,
	0x97, 0x9b, 0x03, 0x89, 0x5b, 0x9c, 0xda, 0x9c, 0xd6, 0x21, 0xca, 0xf3, 0x7e, 0x78, 0x4c, 0x9f,
	0xd3, 0xfe, 0x40, 0x2f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0xb9, 0xac, 0x9b, 0x2f, 0x01,
	0x00, 0x00,
}
